<a href="https://colab.research.google.com/github/lakshmivisalij/cab/blob/master/Skikit%20Learn%20Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [0]:
data = np.random.randint(0,100,(10,2))

In [4]:
data

array([[27, 99],
       [99, 99],
       [71, 76],
       [ 0, 66],
       [38, 42],
       [83, 47],
       [89, 48],
       [94, 42],
       [31, 28],
       [82, 48]])

In [0]:
scaler_model = MinMaxScaler()

In [6]:
type(scaler_model)

sklearn.preprocessing.data.MinMaxScaler

In [8]:
scaler_model.fit(data)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [10]:
scaler_model.transform(data)

array([[0.27272727, 1.        ],
       [1.        , 1.        ],
       [0.71717172, 0.67605634],
       [0.        , 0.53521127],
       [0.38383838, 0.1971831 ],
       [0.83838384, 0.26760563],
       [0.8989899 , 0.28169014],
       [0.94949495, 0.1971831 ],
       [0.31313131, 0.        ],
       [0.82828283, 0.28169014]])

In [11]:
scaler_model.fit_transform(data)

array([[0.27272727, 1.        ],
       [1.        , 1.        ],
       [0.71717172, 0.67605634],
       [0.        , 0.53521127],
       [0.38383838, 0.1971831 ],
       [0.83838384, 0.26760563],
       [0.8989899 , 0.28169014],
       [0.94949495, 0.1971831 ],
       [0.31313131, 0.        ],
       [0.82828283, 0.28169014]])

In [0]:
import pandas as pd

In [0]:
df = pd.DataFrame(data = np.random.randint(0,101,(50,4)), columns = ['f1', 'f2','f3', 'label'])

In [17]:
df

    f1  f2  f3  label
0   53  10   7      5
1   66  25  71     38
2   55  44   9     50
3   62  22  43     56
4   42  24  50     89
5   28  86  31     19
6   43  49   9     37
7    5  82  89     10
8   15  31  69      9
9   25  78   1      2
10  56  48  35      8
11   6  17  89     64
12  82  90  22     10
13  19  87  60     65
14  94  20  15     14
15  24  38  54     67
16  64  35  57     93
17  17  78  86      8
18  38  27  93     51
19  35   4  25     78
20  94  65  32     21
21  97  56  33     92
22  91  51  39     32
23  13  74  35     79
24  40  94   8     30
25  30  55  98     81
26  13  13  72     95
27   3  36  87     75
28  68  76  93     95
29  10  71  91     62
30  55  29   6     83
31  89  55  98     94
32  18  43   2     77
33  81  42  33     83
34  27  94   3     43
35   3  30   5     92
36  67  56  35     99
37  70  68  42      0
38  55  68   7     43
39  33  30  27     29
40  32  54  10     71
41  94  84  77     24
42  84  10  19     51
43  58  11  88     60
44  16  92  19     22
45  61  24  55     44
46  49  73  54      4
47  25  31  40     90
48  59  39  94     75
49   0  21  99     19

In [15]:
df

TypeError: ignored

can also be written in two lines as
myData = np.random.randint(0,101,(50,4))
df = pd.DataFrame(data=myData, columns = ['f1', 'f2', 'f3', 'label'])
df

In [0]:
X = df[['f1','f2','f3']]

In [25]:
X

    f1  f2  f3
0   53  10   7
1   66  25  71
2   55  44   9
3   62  22  43
4   42  24  50
5   28  86  31
6   43  49   9
7    5  82  89
8   15  31  69
9   25  78   1
10  56  48  35
11   6  17  89
12  82  90  22
13  19  87  60
14  94  20  15
15  24  38  54
16  64  35  57
17  17  78  86
18  38  27  93
19  35   4  25
20  94  65  32
21  97  56  33
22  91  51  39
23  13  74  35
24  40  94   8
25  30  55  98
26  13  13  72
27   3  36  87
28  68  76  93
29  10  71  91
30  55  29   6
31  89  55  98
32  18  43   2
33  81  42  33
34  27  94   3
35   3  30   5
36  67  56  35
37  70  68  42
38  55  68   7
39  33  30  27
40  32  54  10
41  94  84  77
42  84  10  19
43  58  11  88
44  16  92  19
45  61  24  55
46  49  73  54
47  25  31  40
48  59  39  94
49   0  21  99

In [0]:
y = df[['label']]

In [21]:
y

    label
0       5
1      38
2      50
3      56
4      89
5      19
6      37
7      10
8       9
9       2
10      8
11     64
12     10
13     65
14     14
15     67
16     93
17      8
18     51
19     78
20     21
21     92
22     32
23     79
24     30
25     81
26     95
27     75
28     95
29     62
30     83
31     94
32     77
33     83
34     43
35     92
36     99
37      0
38     43
39     29
40     71
41     24
42     51
43     60
44     22
45     44
46      4
47     90
48     75
49     19

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3, random_state=101)

In [27]:
X_train.shape

(35, 3)

In [28]:
X_test.shape

(15, 3)